/* Supabase Auth + PostgREST using browser fetch. Access tokens stay in memory. */
(() => {
let token=null,user=null;const config=window.PlayCloudConfig||{},esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function init(){const el=document.getElementById('cloud-plans');if(!el)return;let configured=false;try{const url=new URL(config.supabaseUrl);configured=url.protocol==='https:'&&url.hostname.endsWith('.supabase.co')&&/^sb_publishable_/.test(config.publishableKey);}catch(_){}
 el.innerHTML=`<span class="eyebrow">OPTIONAL / SUPABASE PLAN VAULT</span><h3>Keep your plan across devices.</h3><p>Save module choices, cost assumptions, competitor notes and pitch evidence to your own account. Source code, model keys and repository graph contents are excluded.</p><p class="cloud-state" role="status">${configured?'Cloud project configured. Sign in with an existing email/password account.':'Cloud storage is not configured. Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY at build time and apply the database migration. Local exports remain available.'}</p><form data-cloud-login class="form-grid"><label>Email<input name="email" type="email" autocomplete="username" required ${configured?'':'disabled'}></label><label>Password<input name="password" type="password" autocomplete="current-password" required ${configured?'':'disabled'}></label><button class="secondary" ${configured?'':'disabled'}>Sign in</button></form><div class="button-row"><button class="primary" data-cloud="save" disabled>Save current plan</button><button class="secondary" data-cloud="list" disabled>Find my plans</button><button class="quiet" data-cloud="out" disabled>Sign out</button></div><div data-cloud-list></div><p class="help">Accounts are created or invited through your Supabase project. Sign-in credentials go only to its Auth endpoint. Sessions last in this tab until sign-out or token expiry.</p>`;
 const status=message=>el.querySelector('[role=status]').textContent=message;
 const buttons=()=>el.querySelectorAll('[data-cloud]').forEach(b=>b.disabled=!user);
 async function request(path,options={}){const response=await fetch(config.supabaseUrl.replace(/\/$/,'')+path,{...options,headers:{apikey:config.publishableKey,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers}});if(!response.ok){if(response.status===401){token=null;user=null;buttons();}throw Error('Cloud request failed ('+response.status+'). Check your sign-in, project configuration and owner-access policies.');}return response.status===204?null:response.json();}
 el.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const form=new FormData(e.target);const result=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})});token=result.access_token;user=result.user;if(!token||!user?.id)throw Error('Invalid auth response.');e.target.password.value='';status('Signed in. Your plan is private to this account.');buttons();}catch(error){status(error.message);}finally{button.disabled=false;}};
 el.addEventListener('click',async e=>{const button=e.target.closest('[data-cloud]');if(!button)return;const action=button.dataset.cloud;button.disabled=true;try{
 if(action==='out'){try{await request('/auth/v1/logout',{method:'POST'});}finally{token=null;user=null;el.querySelector('[data-cloud-list]').replaceChildren();status('Signed out.');}}
 if(action==='save'){const payload=window.CreatorWorkbench.exportData();const title=payload.pitch?.company||'Creator venture plan';await request('/rest/v1/creator_plans',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:user.id,title:title.slice(0,200),payload})});status('Plan saved as a new private snapshot.');}
 if(action==='list'){const plans=await request('/rest/v1/creator_plans?select=id,title,created_at&order=created_at.desc&limit=20');el.querySelector('[data-cloud-list]').innerHTML=plans.map(p=>`<p>${esc(p.title)} · ${esc(p.created_at.slice(0,10))} <button class="quiet" data-load="${esc(p.id)}">Load this plan</button></p>`).join('')||'<p>No saved plans yet.</p>';status('Choose a snapshot. Loading replaces this tab’s current module and business assumptions.');}
 }catch(error){status(error.message);}finally{buttons();}});
 el.addEventListener('click',async e=>{const id=e.target.closest('[data-load]')?.dataset.load;if(!id)return;try{if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid plan ID.');const rows=await request('/rest/v1/creator_plans?id=eq.'+id+'&select=payload&limit=1');if(!rows.length)throw Error('Plan unavailable.');window.CreatorWorkbench.loadData(rows[0].payload);status('Saved planning assumptions loaded. Complete the local repository walkthrough to create a workspace.');}catch(error){status(error.message);}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
