'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Blocks,Play,Square,ExternalLink,Download,RefreshCw,KeyRound,Workflow} from 'lucide-react';
import {describeSnapshot,downloadJSON,type Snapshot} from '@/lib/graph';
import {integrationCatalog} from '@/lib/integration-catalog';
import ExecutionEconomics from './ExecutionEconomics';
import type {ExecutionEstimate} from '@/lib/execution-economics';
import {getHarness,type HarnessId,type ProviderMode} from '@/lib/harness-catalog';

type Field={id:string;label:string;type:string;required?:boolean;options?:({value:string;label:string}|string)[];defaultValue?:string|number;description?:string};
type Integration={id:string;label:string;category:string;mode:string;configured:boolean;modelId?:string;capability:string;statusText:string;operations:{id:string;label:string;description?:string;inputFields?:Field[]}[];inputFields?:Field[]};
type Job={id:string;status:'queued'|'running'|'succeeded'|'failed'|'cancelled';integrationId:string;operation:string;createdAt:string;updatedAt:string;result?:unknown;error?:string;usage?:unknown};
const harnesses=[['codex','Codex'],['claude-code','Claude Code'],['cursor','Cursor'],['antigravity','Antigravity'],['opencode','OpenCode'],['hermes','Hermes']];
const terminal=new Set(['succeeded','failed','cancelled']);

export default function IntegrationsPanel({graph,viewGraph}:{graph:Snapshot;viewGraph?:Snapshot}){
 const [items,setItems]=useState<Integration[]>([]),[selected,setSelected]=useState('kernel-suite'),[operation,setOperation]=useState(''),[parameters,setParameters]=useState<Record<string,string>>({});
 const [harnessId,setHarnessId]=useState<HarnessId>('codex' as HarnessId),[provider,setProvider]=useState<ProviderMode>('openrouter' as ProviderMode),[estimate,setEstimate]=useState<ExecutionEstimate|null>(null);
 const [scope,setScope]=useState<'view'|'full'>(viewGraph?'view':'full');
 const executionGraph=scope==='view'&&viewGraph?viewGraph:graph;
 const [token,setToken]=useState(''),[goal,setGoal]=useState('Explain this repository, identify its main dependencies and propose the smallest evidence-backed improvement.'),[includeGraph,setIncludeGraph]=useState(true),[job,setJob]=useState<Job|null>(null),[jobSnapshot,setJobSnapshot]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const active=useRef<AbortController|null>(null),pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true);
 const snapshot=useMemo(()=>describeSnapshot(executionGraph),[executionGraph]);
 const integration=items.find(item=>item.id===selected),source=integrationCatalog.find(item=>item.id===selected);
 const harness=getHarness(harnessId);
 const selectedOperation=integration?.operations.find(item=>item.id===operation);
 const fields=selectedOperation?.inputFields||integration?.inputFields||[];
 const running=busy||Boolean(job&&!terminal.has(job.status));
 const refresh=useCallback(async()=>{try{const response=await fetch('/api/integrations');if(!response.ok)throw Error('Could not read integration configuration.');const body=await response.json();if(mounted.current){setItems(body.integrations||[]);setError('');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Could not read integrations.');}},[]);
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;active.current?.abort();if(pollTimer.current)clearTimeout(pollTimer.current);};},[refresh]);
 useEffect(()=>{const first=integration?.operations[0];setOperation(first?.id||'');setParameters({});if(selected==='openrouter'||selected==='vllm')setProvider(selected);else if(integration?.category==='kernel'||selected==='kernel-suite')setProvider('manual');},[selected,integration]);
 async function readResponse(response:Response){const body=await response.json();if(!response.ok)throw Error(body.error||`Request failed (${response.status}).`);return body;}
 async function poll(id:string,authorization:string,signal:AbortSignal){
  try{const body=await readResponse(await fetch(`/api/integrations/jobs/${encodeURIComponent(id)}`,{headers:{Authorization:authorization},signal}));if(signal.aborted||!mounted.current)return;setJob(body.job);if(!terminal.has(body.job.status))pollTimer.current=setTimeout(()=>void poll(id,authorization,signal),1200);}
  catch(e){if(!signal.aborted&&mounted.current)setError(e instanceof Error?e.message:'Job status unavailable.');}
 }
 async function start(){
  if(!integration||!operation)return;active.current?.abort();if(pollTimer.current)clearTimeout(pollTimer.current);const controller=new AbortController();active.current=controller;setError('');setBusy(true);setJob(null);setJobSnapshot(`${snapshot.name} · ${snapshot.id}`);
  const values:Record<string,string|number>={};for(const field of fields){const value=parameters[field.id]??field.defaultValue;if(value!==undefined&&value!=='')values[field.id]=field.type==='number'?Number(value):String(value);}
  if(selected==='harness')values.harnessId=String(harnessId);
  try{const authorization=`Bearer ${token}`;const body=await readResponse(await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:authorization},body:JSON.stringify({integrationId:selected,operation,input:{goal,parameters:values,...(includeGraph?{graph:executionGraph}:{})}}),signal:controller.signal}));if(controller.signal.aborted||!mounted.current)return;setJob(body.job);if(!terminal.has(body.job.status))void poll(body.job.id,authorization,controller.signal);}
  catch(e){if(!controller.signal.aborted&&mounted.current)setError(e instanceof Error?e.message:'Could not start integration.');}
  finally{if(mounted.current&&active.current===controller)setBusy(false);}
 }
 async function cancel(){if(!job)return;try{const body=await readResponse(await fetch(`/api/integrations/jobs/${encodeURIComponent(job.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}}));setJob(body.job);if(terminal.has(body.job.status)){active.current?.abort();if(pollTimer.current)clearTimeout(pollTimer.current);}}catch(e){setError(e instanceof Error?e.message:'Cancellation failed.');}}
 function exportPlan(){downloadJSON('agent-execution-plan.json',{version:1,createdAt:new Date().toISOString(),snapshot,harnessId,billingProvider:provider,integrationId:selected,operation,goal,parameters,estimate,source:source||null,execution:'Plan only; importing this file does not start a job.'});}
 return <section className="integrations-panel" id="integrations"><header className="integration-heading"><div><span className="eyebrow"><Blocks size={13}/>CONNECTED INTELLIGENCE</span><h2>Your tools. One evidence trail.</h2><p>Choose a framework or kernel, run a bounded task, and inspect its real result.</p></div><button className="secondary-button" onClick={exportPlan}><Download size={14}/>Export execution plan</button></header>
 <div className="integration-layout"><div className="integration-setup"><label>Framework or kernel<select value={selected} disabled={running} onChange={e=>setSelected(e.target.value)}>{items.length?items.map(item=><option key={item.id} value={item.id}>{item.label}{item.configured?'':' · setup required'}</option>):<option value="kernel-suite">Loading integration registry…</option>}</select></label>
 <div className="integration-status"><span className={`pill ${integration?.configured?'configured':''}`}>{integration?.configured?'Configured':'Not configured'}</span><span>{integration?.mode||'Checking runtime'}</span><button className="icon-button" aria-label="Refresh integration configuration" onClick={()=>void refresh()}><RefreshCw size={14}/></button></div><p className="help-text">{integration?.statusText||'Reading available adapters from the local server.'}</p>
 <label>Operation<select value={operation} disabled={running||!integration?.operations.length} onChange={e=>setOperation(e.target.value)}>{integration?.operations.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><p className="help-text">{selectedOperation?.description}</p>{integration?.modelId&&<p className="help-text">Execution model: <strong>{integration.modelId}</strong>. Match this model in your cost assumptions.</p>}
 <label>Preferred coding harness<select value={harnessId} disabled={running} onChange={e=>setHarnessId(e.target.value as HarnessId)}>{harnesses.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {harness&&<details className="integration-source"><summary>Harness authentication & billing</summary>{harness.billingNotes.map((note,i)=><p className="help-text" key={i}>{note}</p>)}</details>}
 <label>Billing scenario<select value={provider} onChange={e=>setProvider(e.target.value as ProviderMode)}><option value="openrouter">OpenRouter API</option><option value="vllm">Self-hosted vLLM</option><option value="subscription">Existing harness subscription</option><option value="gateway">AI Gateway / provider API</option><option value="manual">Custom rates / manual handoff</option></select></label><p className="help-text">Harness selection applies to harness runs and exported plans. External frameworks use their own configured models. The billing scenario estimates costs; it does not change provider credentials.</p>
 {source&&<details className="integration-source"><summary>Verified source & constraints</summary><a href={source.repository} target="_blank" rel="noreferrer">{source.name}<ExternalLink size={12}/></a><p>{source.surface} · {source.runtime}</p><p>Revision: <code>{source.revision}</code></p><p>License: {source.license}</p>{source.constraints.map((note,i)=><p className="help-text" key={i}>{note}</p>)}</details>}
 </div><div className="integration-run"><label>Task goal<textarea value={goal} onChange={e=>setGoal(e.target.value)} maxLength={4000} rows={3} disabled={running}/></label>
 {fields.filter(field=>field.id!=='graph'&&(selected!=='harness'||field.id!=='harnessId')).map(field=><label key={field.id}>{field.label}{field.required?' *':''}{field.type==='select'?<select value={parameters[field.id]??String(field.defaultValue??'')} onChange={e=>setParameters(prev=>({...prev,[field.id]:e.target.value}))} disabled={running}><option value="">Choose…</option>{field.options?.map(option=>{const value=typeof option==='string'?option:option.value;return <option key={value} value={value}>{typeof option==='string'?option:option.label}</option>;})}</select>:<input type={field.type==='number'?'number':'text'} value={parameters[field.id]??String(field.defaultValue??'')} onChange={e=>setParameters(prev=>({...prev,[field.id]:e.target.value}))} disabled={running} maxLength={2000}/>}<small>{field.description}</small></label>)}
 <label>Repository scope<select value={scope} disabled={running} onChange={e=>setScope(e.target.value as 'view'|'full')}><option value="view" disabled={!viewGraph}>Current filtered graph view</option><option value="full">Full repository snapshot</option></select></label><label className="include-graph"><input type="checkbox" checked={includeGraph} onChange={e=>setIncludeGraph(e.target.checked)} disabled={running}/><span>{integration?.mode==='local_bridge'?'Include snapshot name and counts only:':'Send this repository snapshot:'} {executionGraph.nodes.length.toLocaleString()} nodes and {executionGraph.edges.length.toLocaleString()} relationships.</span></label>
 {integration?.mode==='local_bridge'&&<p className="help-text">The harness runs in its server-configured workspace. This selection sends metadata only; importing a graph does not clone or change that workspace.</p>}
 <label><span><KeyRound size={12}/> Private workspace execution token</span><input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Kept in memory; never included in exports"/></label><p className="help-text">Provider keys and service destinations are configured on the server. Starting a configured job may incur provider charges.</p>
 <div className="button-row"><button className="primary-button" onClick={()=>void start()} disabled={!integration?.configured||!operation||!goal.trim()||!token||running}><Play size={14}/>{busy?'Submitting…':'Run selected operation'}</button>{job&&!terminal.has(job.status)&&<button className="secondary-button" onClick={()=>void cancel()}><Square size={12}/>Cancel job</button>}</div>
 {error&&<p role="alert" className="error-text">{error}</p>}{error&&job&&!terminal.has(job.status)&&<button className="secondary-button" onClick={()=>{setError('');active.current?.abort();const controller=new AbortController();active.current=controller;void poll(job.id,`Bearer ${token}`,controller.signal);}}>Retry status check</button>}
 {job&&<div className="integration-job" aria-live="polite"><div><Workflow size={15}/><strong>{job.status}</strong><code>{job.id}</code></div><p>{job.integrationId} / {job.operation} · {jobSnapshot}</p>{job.error&&<p className="error-text">{job.error}</p>}{job.result!==undefined&&<details open><summary>Execution result</summary><pre>{typeof job.result==='string'?job.result:JSON.stringify(job.result,null,2)}</pre></details>}{job.usage!==undefined&&<details><summary>Reported usage</summary><pre>{JSON.stringify(job.usage,null,2)}</pre></details>}</div>}
 <p className="help-text">“Succeeded” means this adapter request completed. For submitted remote workflows, use the returned identifiers with the status operation to confirm completion.</p>
 <p className="help-text">Job tracking is local to this server process. A page reload or server restart is not durable orchestration; remote cancellation depends on the adapter.</p></div></div>
 <p className="help-text">{integration?.mode==='local_python'?'This selected kernel runs locally without model API calls. Its compute cost depends on your hosting allocation; model-token scenarios below apply only if you add model or harness work.':'Cost assumptions below describe your chosen workload; external framework fees and model settings must be entered explicitly.'}</p>
 <ExecutionEconomics workloadKind={integration?.mode==='local_python'?'kernel':selected==='harness'?'harness':['openrouter','vllm'].includes(selected)?'model':'framework'} harnessId={harnessId} provider={provider} onEstimate={setEstimate}/>
 </section>;
}
